---
galaxy_info:
  role_name: role_splunk_install
  namespace: constructingdefenselab
  author: Anton Ovrutsky
  description: Install Splunk Enterprise on the domain controller with optimized timing
  license: GPLv3
  min_ansible_version: "2.9"
  version: "1.1.0"
  platforms:
    - name: Windows
      versions:
        - all
  galaxy_tags:
    - splunk
    - windows

dependencies: []

collections:
  - ansible.windows
