---
galaxy_info:
  role_name: role_splunk_collector_linuxv
  namespace: constructingdefenselab
  author: Anton Ovrutsky
  description: Install Splunk Universal Forwarder on Linux with boot-start enabled
  license: GPLv3
  min_ansible_version: "2.9"
  version: "1.2.0"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - splunk
    - forwarder
    - linux

dependencies: []

collections: []
