---
galaxy_info:
  role_name: role_malcolm_install
  namespace: constructingdefenselab
  author: Anton Ovrutsky
  description: Install Malcolm (Zeek/Suricata/Arkime) with low-resource tuning
  license: GPLv3
  min_ansible_version: "2.9"
  version: "1.1.0"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - malcolm
    - pcap
    - network_security

dependencies: []

collections: []
