---
galaxy_info:
  role_name: role_k3s
  namespace: constructingdefenselab
  author: Anton Ovrutsky
  description: Install lightweight k3s Kubernetes cluster on Debian
  license: GPLv3
  min_ansible_version: "2.9"
  version: "1.0.0"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - k3s
    - debian

dependencies: []

collections: []
